 spring:
  application:
    name: EmployeeManagementSystemApplication
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: mysql://localhost:3306/employee-management-system_data_jpa?createDatabaseIfNotExist=true
    username: root
    password: Subha@14101995
  jpa:
    show-sql: true
    properties:
      format_sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081
